[project]
name = "product-db-models"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "geoalchemy2>=0.18.0",
    "sqlalchemy>=2.0.43",
]
