"""enforce unique article-concept association

Revision ID: 3734a324ea3b
Revises: 3a640e38e6f4
Create Date: 2025-09-19 14:55:54.624852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3734a324ea3b'
down_revision: Union[str, Sequence[str], None] = '3a640e38e6f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geo_taxonomy_concept_uris',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('uri', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'uri', name='unique_name_uri')
    )
    op.alter_column('article_concept_association', 'article_uri',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('article_concept_association', 'concept_uri',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key(None, 'article_concept_association', 'article_downloads', ['article_uri'], ['uri'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'article_concept_association', type_='foreignkey')
    op.alter_column('article_concept_association', 'concept_uri',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('article_concept_association', 'article_uri',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_table('geo_taxonomy_concept_uris')
    # ### end Alembic commands ###
