"""allow duplicates in URI requests

Revision ID: 3a640e38e6f4
Revises: aa6f20678a45
Create Date: 2025-09-09 09:46:29.272858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a640e38e6f4'
down_revision: Union[str, Sequence[str], None] = 'aa6f20678a45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('article_uris_uri_key'), 'article_uris', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('article_uris_uri_key'), 'article_uris', ['uri'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
