"""Move article_downloads to articles schema

Revision ID: 7ac3862c13d2
Revises: bc41f02a2341
Create Date: 2026-03-27 11:05:55.580273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7ac3862c13d2'
down_revision: Union[str, Sequence[str], None] = 'bc41f02a2341'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_downloads',
    sa.Column('uri', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('source_uri', sa.String(), nullable=True),
    sa.Column('cloud_uri', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('is_duplicate', sa.Boolean(), nullable=True),
    sa.Column('article_type', postgresql.ENUM('pr', 'blog', 'news', name='article_enum', schema='articles'), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uri'),
    sa.UniqueConstraint('cloud_uri'),
    schema='articles'
    )
    op.create_index(op.f('ix_articles_article_downloads_article_type'), 'article_downloads', ['article_type'], unique=False, schema='articles')
    op.create_index(op.f('ix_articles_article_downloads_language'), 'article_downloads', ['language'], unique=False, schema='articles')
    op.create_table('risk_factor_scores',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('risk_factor_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('adm_code', sa.String(), nullable=False),
    sa.Column('year_month', sa.Date(), nullable=False),
    sa.CheckConstraint('EXTRACT(DAY FROM year_month) = 1', name='chk_risk_factor_scores_month_first_day'),
    sa.ForeignKeyConstraint(['adm_code'], ['geo_taxonomy.adm_code'], name='fk_risk_factor_scores_adm_code'),
    sa.ForeignKeyConstraint(['risk_factor_id'], ['risk_factors.id'], name='fk_risk_factor_scores_risk_factor_id'),
    sa.PrimaryKeyConstraint('adm_code', 'year_month', 'risk_factor_id', name='pk_risk_factor_scores')
    )
    op.drop_constraint(op.f('fk_article_concept_association_article_uri'), 'article_concept_association', type_='foreignkey')
    op.create_foreign_key('fk_article_concept_association_article_uri', 'article_concept_association', 'article_downloads', ['article_uri'], ['uri'], referent_schema='articles')
    op.create_foreign_key('fk_article_concept_association_concept_uri', 'article_concept_association', 'concept_uris', ['concept_uri'], ['concept_uri'])
    op.drop_constraint(op.f('fk_article_location_tags_article_uri'), 'article_location_tags', type_='foreignkey')
    op.create_foreign_key('fk_%(table_name)s_article_uri', 'article_location_tags', 'article_downloads', ['article_uri'], ['uri'], referent_schema='articles')
    op.drop_constraint(op.f('fk_article_risk_factor_tags_article_uri'), 'article_risk_factor_tags', type_='foreignkey')
    op.create_foreign_key('fk_%(table_name)s_article_uri', 'article_risk_factor_tags', 'article_downloads', ['article_uri'], ['uri'], referent_schema='articles')
    op.drop_constraint(op.f('fk_tagged_articles_article_uri'), 'tagged_articles', type_='foreignkey')
    op.create_foreign_key('fk_tagged_articles_article_uri', 'tagged_articles', 'article_downloads', ['article_uri'], ['uri'], referent_schema='articles')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_tagged_articles_article_uri', 'tagged_articles', type_='foreignkey')
    op.create_foreign_key(op.f('fk_tagged_articles_article_uri'), 'tagged_articles', 'article_downloads_bak', ['article_uri'], ['uri'])
    op.drop_constraint('fk_%(table_name)s_article_uri', 'article_risk_factor_tags', type_='foreignkey')
    op.create_foreign_key(op.f('fk_article_risk_factor_tags_article_uri'), 'article_risk_factor_tags', 'article_downloads_bak', ['article_uri'], ['uri'])
    op.drop_constraint('fk_%(table_name)s_article_uri', 'article_location_tags', type_='foreignkey')
    op.create_foreign_key(op.f('fk_article_location_tags_article_uri'), 'article_location_tags', 'article_downloads_bak', ['article_uri'], ['uri'])
    op.drop_constraint('fk_article_concept_association_concept_uri', 'article_concept_association', type_='foreignkey')
    op.drop_constraint('fk_article_concept_association_article_uri', 'article_concept_association', type_='foreignkey')
    op.create_foreign_key(op.f('fk_article_concept_association_article_uri'), 'article_concept_association', 'article_downloads_bak', ['article_uri'], ['uri'])
    op.drop_table('risk_factor_scores')
    op.drop_index(op.f('ix_articles_article_downloads_language'), table_name='article_downloads', schema='articles')
    op.drop_index(op.f('ix_articles_article_downloads_article_type'), table_name='article_downloads', schema='articles')
    op.drop_table('article_downloads', schema='articles')
    # ### end Alembic commands ###
