"""Add URL to article download table

Revision ID: bc41f02a2341
Revises: 1f0c7e30baff
Create Date: 2026-02-23 13:08:51.265915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc41f02a2341'
down_revision: Union[str, Sequence[str], None] = '1f0c7e30baff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_factor_scores',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('risk_factor_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('adm_code', sa.String(), nullable=False),
    sa.Column('year_month', sa.Date(), nullable=False),
    sa.CheckConstraint('EXTRACT(DAY FROM year_month) = 1', name='chk_risk_factor_scores_month_first_day'),
    sa.ForeignKeyConstraint(['adm_code'], ['geo_taxonomy.adm_code'], name='fk_risk_factor_scores_adm_code'),
    sa.ForeignKeyConstraint(['risk_factor_id'], ['risk_factors.id'], name='fk_risk_factor_scores_risk_factor_id'),
    sa.PrimaryKeyConstraint('adm_code', 'year_month', 'risk_factor_id', name='pk_risk_factor_scores')
    )
    op.create_foreign_key('fk_article_concept_association_concept_uri', 'article_concept_association', 'concept_uris', ['concept_uri'], ['concept_uri'])
    op.add_column('article_downloads', sa.Column('url', sa.String(), nullable=True))
    op.drop_index(op.f('ix_article_downloads_published_at'), table_name='article_downloads')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_article_downloads_published_at'), 'article_downloads', [sa.literal_column('(published_at::date)')], unique=False)
    op.drop_column('article_downloads', 'url')
    op.drop_constraint('fk_article_concept_association_concept_uri', 'article_concept_association', type_='foreignkey')
    op.drop_table('risk_factor_scores')
    # ### end Alembic commands ###
