"""Associate risk factors and concept URIs

Revision ID: c2a9585342f0
Revises: ba79db50c198
Create Date: 2026-01-15 14:37:59.406817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2a9585342f0'
down_revision: Union[str, Sequence[str], None] = 'ba79db50c198'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_insecurity_scores',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('adm_code', sa.String(), nullable=False),
    sa.Column('year_month', sa.Date(), nullable=False),
    sa.CheckConstraint('EXTRACT(DAY FROM year_month) = 1', name='chk_month_first_day'),
    sa.PrimaryKeyConstraint('adm_code', 'year_month', name='pk_food_insecurity_scores')
    )
    op.create_table('risk_factor_concepts',
    sa.Column('risk_factor_id', sa.Integer(), nullable=False),
    sa.Column('concept_uri', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['concept_uri'], ['concept_uris.concept_uri'], name='fk_risk_factor_concepts_risk_concept_uri'),
    sa.ForeignKeyConstraint(['risk_factor_id'], ['risk_factors.id'], name='fk_risk_factor_concepts_risk_factor_id'),
    sa.PrimaryKeyConstraint('risk_factor_id', 'concept_uri')
    )
    op.create_index('ix_risk_factor_concepts_concept_uri', 'risk_factor_concepts', ['concept_uri'], unique=False)
    op.create_table('risk_factor_scores',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('risk_factor_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('adm_code', sa.String(), nullable=False),
    sa.Column('year_month', sa.Date(), nullable=False),
    sa.CheckConstraint('EXTRACT(DAY FROM year_month) = 1', name='chk_risk_factor_scores_month_first_day'),
    sa.ForeignKeyConstraint(['risk_factor_id'], ['risk_factors.id'], ),
    sa.PrimaryKeyConstraint('risk_factor_id', 'adm_code', 'year_month', name='pk_risk_factor_scores')
    )
    op.create_foreign_key('fk_article_concept_association_concept_uri', 'article_concept_association', 'concept_uris', ['concept_uri'], ['concept_uri'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_article_concept_association_concept_uri', 'article_concept_association', type_='foreignkey')
    op.drop_table('risk_factor_scores')
    op.drop_index('ix_risk_factor_concepts_concept_uri', table_name='risk_factor_concepts')
    op.drop_table('risk_factor_concepts')
    op.drop_table('food_insecurity_scores')
    # ### end Alembic commands ###
