"""Track tag locations within the article body

Revision ID: c5bc6f95a217
Revises: d0349b892ef1
Create Date: 2025-12-01 09:36:44.129115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5bc6f95a217'
down_revision: Union[str, Sequence[str], None] = 'd0349b892ef1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_insecurity_scores',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('adm_code', sa.String(), nullable=False),
    sa.Column('year_month', sa.Date(), nullable=False),
    sa.CheckConstraint('EXTRACT(DAY FROM year_month) = 1', name='chk_month_first_day'),
    sa.PrimaryKeyConstraint('adm_code', 'year_month', name='pk_food_insecurity_scores')
    )
    op.create_table('risk_factor_scores',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('risk_factor_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('adm_code', sa.String(), nullable=False),
    sa.Column('year_month', sa.Date(), nullable=False),
    sa.CheckConstraint('EXTRACT(DAY FROM year_month) = 1', name='chk_risk_factor_scores_month_first_day'),
    sa.ForeignKeyConstraint(['risk_factor_id'], ['risk_factors.id'], ),
    sa.PrimaryKeyConstraint('risk_factor_id', 'adm_code', 'year_month', name='pk_risk_factor_scores')
    )
    op.create_foreign_key('fk_article_concept_association_concept_uri', 'article_concept_association', 'concept_uris', ['concept_uri'], ['concept_uri'])
    op.add_column('article_location_tags', sa.Column('article_position_group', sa.String(), nullable=True))
    op.add_column('article_location_tags', sa.Column('article_position_start', sa.Integer(), nullable=True))
    op.add_column('article_location_tags', sa.Column('article_position_end', sa.Integer(), nullable=True))
    op.add_column('article_risk_factor_tags', sa.Column('article_position_group', sa.String(), nullable=True))
    op.add_column('article_risk_factor_tags', sa.Column('article_position_start', sa.Integer(), nullable=True))
    op.add_column('article_risk_factor_tags', sa.Column('article_position_end', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article_risk_factor_tags', 'article_position_end')
    op.drop_column('article_risk_factor_tags', 'article_position_start')
    op.drop_column('article_risk_factor_tags', 'article_position_group')
    op.drop_column('article_location_tags', 'article_position_end')
    op.drop_column('article_location_tags', 'article_position_start')
    op.drop_column('article_location_tags', 'article_position_group')
    op.drop_constraint('fk_article_concept_association_concept_uri', 'article_concept_association', type_='foreignkey')
    op.drop_table('risk_factor_scores')
    op.drop_table('food_insecurity_scores')
    # ### end Alembic commands ###
