"""Create article query and uri models

Revision ID: cfd82b7ec7ff
Revises: b98b96b9d218
Create Date: 2025-09-02 15:40:03.587884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cfd82b7ec7ff'
down_revision: Union[str, Sequence[str], None] = 'b98b96b9d218'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_queries',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('body', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('article_uris',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uri', sa.String(), nullable=False),
    sa.Column('query_uuid', sa.UUID(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('queried_at', sa.DateTime(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['query_uuid'], ['article_queries.uuid'], name='fk_article_uris_query_uuid'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uri')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article_uris')
    op.drop_table('article_queries')
    # ### end Alembic commands ###
